name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # ✅ 建议升级为与你本地一致的版本

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install bump-my-version
          pip install -r requirements.txt

      - name: Check dependency versions
        run: python check-deps.py

      - name: Run lint checks
        run: bash scripts/lint.sh

      - name: Run tests
        run: pytest

      - name: Bump patch version
        run: bump-my-version patch

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
